//! VP8 decoder constant tables.
//!
//! Translated literally from `vp8/common/*.c` (libvpx). Every table here
//! is a fixed bitstream constant from RFC 6386 — none are mutated at
//! runtime. The doc comment on each item points back to the originating
//! RFC section and to the C source file.
//!
//! This module is generated by `rust/scripts/extract_tables.py`.

#![allow(dead_code)]

// ---------------------------------------------------------------------------
// Type aliases (mirrors of C typedefs in `treecoder.h` / `blockd.h`)
// ---------------------------------------------------------------------------

/// `vp8_prob` from `treecoder.h` — an 8-bit probability in [0, 255]
/// where 0 means "always 0" and 255 means "always 1".
pub type Prob = u8;

/// `vp8_tree_index` from `treecoder.h`. Non-positive values terminate
/// the tree (returned value is `-index`); positive values are byte
/// offsets into the same tree array.
pub type TreeIndex = i8;

/// `vp8_token` (`vp8_token_struct`) — pair of (codeword value, bit length).
#[derive(Copy, Clone, Debug)]
pub struct Token {
    pub value: i32,
    pub len: i32,
}

// ---------------------------------------------------------------------------
// Constants (RFC 6386 — counts of tokens, planes, modes, …)
// ---------------------------------------------------------------------------

/// `vp8_prob_half` — neutral probability used as a default. RFC 6386 §7.
pub const PROB_HALF: Prob = 128;

/// Maximum probability value. RFC 6386 §7.
pub const MAX_PROB: Prob = 255;

/// `MAX_ENTROPY_TOKENS` — size of the coefficient token alphabet. RFC 6386 §13.
pub const MAX_ENTROPY_TOKENS: usize = 12;

/// `ENTROPY_NODES` — number of internal nodes in the coefficient tree.
pub const ENTROPY_NODES: usize = 11;

/// `BLOCK_TYPES` — outer dimension of the coefficient probability table:
/// 0 = Y no DC, 1 = Y2, 2 = UV, 3 = Y with DC. RFC 6386 §13.3.
pub const BLOCK_TYPES: usize = 4;

/// `COEF_BANDS` — coarsening of position within a 4x4 DCT block. RFC 6386 §13.3.
pub const COEF_BANDS: usize = 8;

/// `PREV_COEF_CONTEXTS` — 3-valued measure of nearby coefficient complexity.
pub const PREV_COEF_CONTEXTS: usize = 3;

/// `DCT_MAX_VALUE` — clipping bound for dequantized DCT coefficients.
pub const DCT_MAX_VALUE: i32 = 2048;

/// `MAXQ` — largest legal quantizer index (RFC 6386 §9.6).
pub const MAXQ: usize = 127;
/// `QINDEX_RANGE` — count of legal quantizer indices.
pub const QINDEX_RANGE: usize = MAXQ + 1;

/// `VP8_BINTRAMODES` — number of intra modes for a 4x4 sub-block. RFC 6386 §11.5.
pub const VP8_BINTRAMODES: usize = 10;
/// `VP8_YMODES` — number of macroblock-level intra Y modes. RFC 6386 §11.2.
pub const VP8_YMODES: usize = 5;
/// `VP8_UV_MODES` — number of intra UV modes. RFC 6386 §11.2.
pub const VP8_UV_MODES: usize = 4;
/// `VP8_MVREFS` — number of inter modes for a macroblock. RFC 6386 §16.2.
pub const VP8_MVREFS: usize = 5;
/// `VP8_SUBMVREFS` — number of inter modes for a 4x4 sub-block. RFC 6386 §17.4.
pub const VP8_SUBMVREFS: usize = 4;
/// `VP8_NUMMBSPLITS` — number of macroblock-partition layouts. RFC 6386 §17.3.
pub const VP8_NUMMBSPLITS: usize = 4;
/// `SUBMVREF_COUNT` — number of sub-MV-ref contexts. RFC 6386 §17.4.
pub const SUBMVREF_COUNT: usize = 5;

/// Sub-pixel filter constants (`filter.h`). RFC 6386 §6.5.
pub const VP8_FILTER_WEIGHT: i32 = 128;
/// Right-shift applied after summing 6-tap (or 2-tap) filter products.
pub const VP8_FILTER_SHIFT: i32 = 7;

// ---------------------------------------------------------------------------
// MV probability shape (`entropymv.h`).
//
//   mvpis_short = 0        // short (<= 7) vs long (>= 8)
//   MVPsign     = 1        // sign for non-zero MV
//   MVPshort    = 2..8     // 8 short values (7-position tree)
//   MVPbits     = 9..18    // 10 long-magnitude bit probabilities
//
// MVPcount = MVPbits + mvlong_width = 9 + 10 = 19.
// ---------------------------------------------------------------------------

/// `mvlong_width` — long MVs have 9 magnitude bits + 1 sign = 10. RFC 6386 §17.1.
pub const MV_LONG_WIDTH: usize = 10;
/// `mvnum_short` — magnitudes 0..7. RFC 6386 §17.1.
pub const MV_NUM_SHORT: usize = 8;
/// `MVPbits` — short tree (7 probs) + is-short + sign offset.
pub const MVP_BITS: usize = 2 + MV_NUM_SHORT - 1; // 9
/// `MVPcount` — total per-component MV probabilities.
pub const MVP_COUNT: usize = MVP_BITS + MV_LONG_WIDTH; // 19

/// `MV_CONTEXT` — per-component MV probability vector. RFC 6386 §17.1.
#[derive(Copy, Clone, Debug)]
pub struct MvContext {
    pub prob: [Prob; MVP_COUNT],
}

// ---------------------------------------------------------------------------
// entropy.c — coefficient entropy tables
// ---------------------------------------------------------------------------

/// `vp8_norm` — leading-zero count used to renormalize the bool decoder's range register. Indexed by the 8-bit range value. RFC 6386 §7.3 (boolean decoder).
#[rustfmt::skip]
pub const VP8_NORM: [u8; 256] = [0, 7, 6, 6, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
/// `vp8_coef_bands` — maps a zig-zag coefficient position (0..15) to one of 8 probability bands. RFC 6386 §13.3 Figure 13-2.
#[rustfmt::skip]
pub const VP8_COEF_BANDS: [u8; 16] = [0, 1, 2, 3, 6, 4, 5, 6, 6, 6, 6, 6, 6, 6, 6, 7];
/// `vp8_prev_token_class` — maps a previously decoded coefficient token to the 0/1/2 context for the next coefficient. RFC 6386 §13.3.
#[rustfmt::skip]
pub const VP8_PREV_TOKEN_CLASS: [u8; 12] = [0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0];
/// `vp8_default_zig_zag1d` — forward zig-zag: maps scan position to raster position within a 4x4 DCT block. RFC 6386 §13.2.
#[rustfmt::skip]
pub const VP8_DEFAULT_ZIG_ZAG1D: [i32; 16] = [0, 1, 4, 8, 5, 2, 3, 6, 9, 12, 13, 10, 7, 11, 14, 15];
/// `vp8_default_inv_zig_zag` — inverse zig-zag. RFC 6386 §13.2.
#[rustfmt::skip]
pub const VP8_DEFAULT_INV_ZIG_ZAG: [i16; 16] = [1, 2, 6, 7, 3, 5, 8, 13, 4, 9, 12, 14, 10, 11, 15, 16];
/// `vp8_default_zig_zag_mask` — bit mask at zig-zag position; value at raster index `r` is `1 << zigzag_index_of(r)`. The last entry is `-32768` (bit 15 in two's complement i16). Derived from the zig-zag order of RFC 6386 §13.2.
#[rustfmt::skip]
pub const VP8_DEFAULT_ZIG_ZAG_MASK: [i16; 16] = [1, 2, 32, 64, 4, 16, 128, 4096, 8, 256, 2048, 8192, 512, 1024, 16384, -32768];
/// `vp8_mb_feature_data_bits` — bit-widths for the two MB-level segment features (alt-Q = 7, alt-LF = 6). RFC 6386 §10.
#[rustfmt::skip]
pub const VP8_MB_FEATURE_DATA_BITS: [i32; 2] = [7, 6];
/// `vp8_coef_tree` — token decoding tree for residual coefficients. Indexed by node, pairs of (left, right) child indices; negative values are terminal token IDs. RFC 6386 §13.5.
#[rustfmt::skip]
pub const VP8_COEF_TREE: [TreeIndex; 22] = [-11, 2, 0, 4, -1, 6, 8, 12, -2, 10, -3, -4, 14, 16, -5, -6, 18, 20, -7, -8, -9, -10];
/// `vp8_coef_encodings` — encoder-side codewords for the residual token tree.
/// Derived from `VP8_COEF_TREE` via `vp8_tokens_from_tree`. RFC 6386 §13.5.
#[rustfmt::skip]
pub const VP8_COEF_ENCODINGS: [Token; MAX_ENTROPY_TOKENS] = [Token { value: 2, len: 2 }, Token { value: 6, len: 3 }, Token { value: 28, len: 5 }, Token { value: 58, len: 6 }, Token { value: 59, len: 6 }, Token { value: 60, len: 6 }, Token { value: 61, len: 6 }, Token { value: 124, len: 7 }, Token { value: 125, len: 7 }, Token { value: 126, len: 7 }, Token { value: 127, len: 7 }, Token { value: 0, len: 1 }];

/// `Pcat1` — extra-bit probabilities for DCT category 1 (RFC 6386 §13.3, Table 13-5).
#[rustfmt::skip]
pub const PCAT1: [Prob; 1] = [159];

/// `Pcat2` — extra-bit probabilities for DCT category 2 (RFC 6386 §13.3, Table 13-5).
#[rustfmt::skip]
pub const PCAT2: [Prob; 2] = [165, 145];

/// `Pcat3` — extra-bit probabilities for DCT category 3 (RFC 6386 §13.3, Table 13-5).
#[rustfmt::skip]
pub const PCAT3: [Prob; 3] = [173, 148, 140];

/// `Pcat4` — extra-bit probabilities for DCT category 4 (RFC 6386 §13.3, Table 13-5).
#[rustfmt::skip]
pub const PCAT4: [Prob; 4] = [176, 155, 140, 135];

/// `Pcat5` — extra-bit probabilities for DCT category 5 (RFC 6386 §13.3, Table 13-5).
#[rustfmt::skip]
pub const PCAT5: [Prob; 5] = [180, 157, 141, 134, 130];

/// `Pcat6` — extra-bit probabilities for DCT category 6 (RFC 6386 §13.3, Table 13-5).
#[rustfmt::skip]
pub const PCAT6: [Prob; 11] = [254, 254, 243, 230, 196, 177, 153, 140, 133, 130, 129];

/// `cat1` — flat-tree for DCT category 1 extra bits (generated by `init_bit_tree`; RFC 6386 §13.3).
#[rustfmt::skip]
pub const CAT1: [TreeIndex; 2] = [0, 0];

/// `cat2` — flat-tree for DCT category 2 extra bits (generated by `init_bit_tree`; RFC 6386 §13.3).
#[rustfmt::skip]
pub const CAT2: [TreeIndex; 4] = [2, 2, 0, 0];

/// `cat3` — flat-tree for DCT category 3 extra bits (generated by `init_bit_tree`; RFC 6386 §13.3).
#[rustfmt::skip]
pub const CAT3: [TreeIndex; 6] = [2, 2, 4, 4, 0, 0];

/// `cat4` — flat-tree for DCT category 4 extra bits (generated by `init_bit_tree`; RFC 6386 §13.3).
#[rustfmt::skip]
pub const CAT4: [TreeIndex; 8] = [2, 2, 4, 4, 6, 6, 0, 0];

/// `cat5` — flat-tree for DCT category 5 extra bits (generated by `init_bit_tree`; RFC 6386 §13.3).
#[rustfmt::skip]
pub const CAT5: [TreeIndex; 10] = [2, 2, 4, 4, 6, 6, 8, 8, 0, 0];

/// `cat6` — flat-tree for DCT category 6 extra bits (generated by `init_bit_tree`; RFC 6386 §13.3).
#[rustfmt::skip]
pub const CAT6: [TreeIndex; 22] = [2, 2, 4, 4, 6, 6, 8, 8, 10, 10, 12, 12, 14, 14, 16, 16, 18, 18, 20, 20, 0, 0];

/// `vp8_extra_bit_struct` — per-token extra-bit description: an optional
/// tree, optional probability table, length, and base value to add.
/// RFC 6386 §13.3 (extra bits for DCT value categories).
#[derive(Copy, Clone, Debug)]
pub struct ExtraBit {
    pub tree: Option<&'static [TreeIndex]>,
    pub prob: Option<&'static [Prob]>,
    pub len: i32,
    pub base_val: i32,
}

/// `vp8_extra_bits` — indexed by token value, see entropy.c.
/// RFC 6386 §13.3 (Token alphabet, "Extra Bits" column).
#[rustfmt::skip]
pub const VP8_EXTRA_BITS: [ExtraBit; 12] = [
    ExtraBit { tree: None,            prob: None,            len: 0,  base_val: 0  },
    ExtraBit { tree: None,            prob: None,            len: 0,  base_val: 1  },
    ExtraBit { tree: None,            prob: None,            len: 0,  base_val: 2  },
    ExtraBit { tree: None,            prob: None,            len: 0,  base_val: 3  },
    ExtraBit { tree: None,            prob: None,            len: 0,  base_val: 4  },
    ExtraBit { tree: Some(&CAT1),     prob: Some(&PCAT1),    len: 1,  base_val: 5  },
    ExtraBit { tree: Some(&CAT2),     prob: Some(&PCAT2),    len: 2,  base_val: 7  },
    ExtraBit { tree: Some(&CAT3),     prob: Some(&PCAT3),    len: 3,  base_val: 11 },
    ExtraBit { tree: Some(&CAT4),     prob: Some(&PCAT4),    len: 4,  base_val: 19 },
    ExtraBit { tree: Some(&CAT5),     prob: Some(&PCAT5),    len: 5,  base_val: 35 },
    ExtraBit { tree: Some(&CAT6),     prob: Some(&PCAT6),    len: 11, base_val: 67 },
    ExtraBit { tree: None,            prob: None,            len: 0,  base_val: 0  },
];

/// `vp8_coef_update_probs` — per-node probability of an in-band update of the corresponding coefficient probability. Indexed `[block_type][band][prev_context][node]`. RFC 6386 §13.5 / `coefupdateprobs.h`.
#[rustfmt::skip]
pub const VP8_COEF_UPDATE_PROBS: [[[[Prob; 11]; 3]; 8]; 4] = [[[[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]], [[176, 246, 255, 255, 255, 255, 255, 255, 255, 255, 255], [223, 241, 252, 255, 255, 255, 255, 255, 255, 255, 255], [249, 253, 253, 255, 255, 255, 255, 255, 255, 255, 255]], [[255, 244, 252, 255, 255, 255, 255, 255, 255, 255, 255], [234, 254, 254, 255, 255, 255, 255, 255, 255, 255, 255], [253, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]], [[255, 246, 254, 255, 255, 255, 255, 255, 255, 255, 255], [239, 253, 254, 255, 255, 255, 255, 255, 255, 255, 255], [254, 255, 254, 255, 255, 255, 255, 255, 255, 255, 255]], [[255, 248, 254, 255, 255, 255, 255, 255, 255, 255, 255], [251, 255, 254, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]], [[255, 253, 254, 255, 255, 255, 255, 255, 255, 255, 255], [251, 254, 254, 255, 255, 255, 255, 255, 255, 255, 255], [254, 255, 254, 255, 255, 255, 255, 255, 255, 255, 255]], [[255, 254, 253, 255, 254, 255, 255, 255, 255, 255, 255], [250, 255, 254, 255, 254, 255, 255, 255, 255, 255, 255], [254, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]], [[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]]], [[[217, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [225, 252, 241, 253, 255, 255, 254, 255, 255, 255, 255], [234, 250, 241, 250, 253, 255, 253, 254, 255, 255, 255]], [[255, 254, 255, 255, 255, 255, 255, 255, 255, 255, 255], [223, 254, 254, 255, 255, 255, 255, 255, 255, 255, 255], [238, 253, 254, 254, 255, 255, 255, 255, 255, 255, 255]], [[255, 248, 254, 255, 255, 255, 255, 255, 255, 255, 255], [249, 254, 255, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]], [[255, 253, 255, 255, 255, 255, 255, 255, 255, 255, 255], [247, 254, 255, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]], [[255, 253, 254, 255, 255, 255, 255, 255, 255, 255, 255], [252, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]], [[255, 254, 254, 255, 255, 255, 255, 255, 255, 255, 255], [253, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]], [[255, 254, 253, 255, 255, 255, 255, 255, 255, 255, 255], [250, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [254, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]], [[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]]], [[[186, 251, 250, 255, 255, 255, 255, 255, 255, 255, 255], [234, 251, 244, 254, 255, 255, 255, 255, 255, 255, 255], [251, 251, 243, 253, 254, 255, 254, 255, 255, 255, 255]], [[255, 253, 254, 255, 255, 255, 255, 255, 255, 255, 255], [236, 253, 254, 255, 255, 255, 255, 255, 255, 255, 255], [251, 253, 253, 254, 254, 255, 255, 255, 255, 255, 255]], [[255, 254, 254, 255, 255, 255, 255, 255, 255, 255, 255], [254, 254, 254, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]], [[255, 254, 255, 255, 255, 255, 255, 255, 255, 255, 255], [254, 254, 255, 255, 255, 255, 255, 255, 255, 255, 255], [254, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]], [[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [254, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]], [[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]], [[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]], [[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]]], [[[248, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [250, 254, 252, 254, 255, 255, 255, 255, 255, 255, 255], [248, 254, 249, 253, 255, 255, 255, 255, 255, 255, 255]], [[255, 253, 253, 255, 255, 255, 255, 255, 255, 255, 255], [246, 253, 253, 255, 255, 255, 255, 255, 255, 255, 255], [252, 254, 251, 254, 254, 255, 255, 255, 255, 255, 255]], [[255, 254, 252, 255, 255, 255, 255, 255, 255, 255, 255], [248, 254, 253, 255, 255, 255, 255, 255, 255, 255, 255], [253, 255, 254, 254, 255, 255, 255, 255, 255, 255, 255]], [[255, 251, 254, 255, 255, 255, 255, 255, 255, 255, 255], [245, 251, 254, 255, 255, 255, 255, 255, 255, 255, 255], [253, 253, 254, 255, 255, 255, 255, 255, 255, 255, 255]], [[255, 251, 253, 255, 255, 255, 255, 255, 255, 255, 255], [252, 253, 254, 255, 255, 255, 255, 255, 255, 255, 255], [255, 254, 255, 255, 255, 255, 255, 255, 255, 255, 255]], [[255, 252, 255, 255, 255, 255, 255, 255, 255, 255, 255], [249, 255, 254, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 254, 255, 255, 255, 255, 255, 255, 255, 255]], [[255, 255, 253, 255, 255, 255, 255, 255, 255, 255, 255], [250, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]], [[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [254, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255], [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]]]];
/// `default_coef_probs` — default per-node coefficient probabilities used to seed the frame at startup or on a key frame. Same indexing as `VP8_COEF_UPDATE_PROBS`. RFC 6386 §13.5 / `default_coef_probs.h`.
#[rustfmt::skip]
pub const DEFAULT_COEF_PROBS: [[[[Prob; 11]; 3]; 8]; 4] = [[[[128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128], [128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128], [128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128]], [[253, 136, 254, 255, 228, 219, 128, 128, 128, 128, 128], [189, 129, 242, 255, 227, 213, 255, 219, 128, 128, 128], [106, 126, 227, 252, 214, 209, 255, 255, 128, 128, 128]], [[1, 98, 248, 255, 236, 226, 255, 255, 128, 128, 128], [181, 133, 238, 254, 221, 234, 255, 154, 128, 128, 128], [78, 134, 202, 247, 198, 180, 255, 219, 128, 128, 128]], [[1, 185, 249, 255, 243, 255, 128, 128, 128, 128, 128], [184, 150, 247, 255, 236, 224, 128, 128, 128, 128, 128], [77, 110, 216, 255, 236, 230, 128, 128, 128, 128, 128]], [[1, 101, 251, 255, 241, 255, 128, 128, 128, 128, 128], [170, 139, 241, 252, 236, 209, 255, 255, 128, 128, 128], [37, 116, 196, 243, 228, 255, 255, 255, 128, 128, 128]], [[1, 204, 254, 255, 245, 255, 128, 128, 128, 128, 128], [207, 160, 250, 255, 238, 128, 128, 128, 128, 128, 128], [102, 103, 231, 255, 211, 171, 128, 128, 128, 128, 128]], [[1, 152, 252, 255, 240, 255, 128, 128, 128, 128, 128], [177, 135, 243, 255, 234, 225, 128, 128, 128, 128, 128], [80, 129, 211, 255, 194, 224, 128, 128, 128, 128, 128]], [[1, 1, 255, 128, 128, 128, 128, 128, 128, 128, 128], [246, 1, 255, 128, 128, 128, 128, 128, 128, 128, 128], [255, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128]]], [[[198, 35, 237, 223, 193, 187, 162, 160, 145, 155, 62], [131, 45, 198, 221, 172, 176, 220, 157, 252, 221, 1], [68, 47, 146, 208, 149, 167, 221, 162, 255, 223, 128]], [[1, 149, 241, 255, 221, 224, 255, 255, 128, 128, 128], [184, 141, 234, 253, 222, 220, 255, 199, 128, 128, 128], [81, 99, 181, 242, 176, 190, 249, 202, 255, 255, 128]], [[1, 129, 232, 253, 214, 197, 242, 196, 255, 255, 128], [99, 121, 210, 250, 201, 198, 255, 202, 128, 128, 128], [23, 91, 163, 242, 170, 187, 247, 210, 255, 255, 128]], [[1, 200, 246, 255, 234, 255, 128, 128, 128, 128, 128], [109, 178, 241, 255, 231, 245, 255, 255, 128, 128, 128], [44, 130, 201, 253, 205, 192, 255, 255, 128, 128, 128]], [[1, 132, 239, 251, 219, 209, 255, 165, 128, 128, 128], [94, 136, 225, 251, 218, 190, 255, 255, 128, 128, 128], [22, 100, 174, 245, 186, 161, 255, 199, 128, 128, 128]], [[1, 182, 249, 255, 232, 235, 128, 128, 128, 128, 128], [124, 143, 241, 255, 227, 234, 128, 128, 128, 128, 128], [35, 77, 181, 251, 193, 211, 255, 205, 128, 128, 128]], [[1, 157, 247, 255, 236, 231, 255, 255, 128, 128, 128], [121, 141, 235, 255, 225, 227, 255, 255, 128, 128, 128], [45, 99, 188, 251, 195, 217, 255, 224, 128, 128, 128]], [[1, 1, 251, 255, 213, 255, 128, 128, 128, 128, 128], [203, 1, 248, 255, 255, 128, 128, 128, 128, 128, 128], [137, 1, 177, 255, 224, 255, 128, 128, 128, 128, 128]]], [[[253, 9, 248, 251, 207, 208, 255, 192, 128, 128, 128], [175, 13, 224, 243, 193, 185, 249, 198, 255, 255, 128], [73, 17, 171, 221, 161, 179, 236, 167, 255, 234, 128]], [[1, 95, 247, 253, 212, 183, 255, 255, 128, 128, 128], [239, 90, 244, 250, 211, 209, 255, 255, 128, 128, 128], [155, 77, 195, 248, 188, 195, 255, 255, 128, 128, 128]], [[1, 24, 239, 251, 218, 219, 255, 205, 128, 128, 128], [201, 51, 219, 255, 196, 186, 128, 128, 128, 128, 128], [69, 46, 190, 239, 201, 218, 255, 228, 128, 128, 128]], [[1, 191, 251, 255, 255, 128, 128, 128, 128, 128, 128], [223, 165, 249, 255, 213, 255, 128, 128, 128, 128, 128], [141, 124, 248, 255, 255, 128, 128, 128, 128, 128, 128]], [[1, 16, 248, 255, 255, 128, 128, 128, 128, 128, 128], [190, 36, 230, 255, 236, 255, 128, 128, 128, 128, 128], [149, 1, 255, 128, 128, 128, 128, 128, 128, 128, 128]], [[1, 226, 255, 128, 128, 128, 128, 128, 128, 128, 128], [247, 192, 255, 128, 128, 128, 128, 128, 128, 128, 128], [240, 128, 255, 128, 128, 128, 128, 128, 128, 128, 128]], [[1, 134, 252, 255, 255, 128, 128, 128, 128, 128, 128], [213, 62, 250, 255, 255, 128, 128, 128, 128, 128, 128], [55, 93, 255, 128, 128, 128, 128, 128, 128, 128, 128]], [[128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128], [128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128], [128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128]]], [[[202, 24, 213, 235, 186, 191, 220, 160, 240, 175, 255], [126, 38, 182, 232, 169, 184, 228, 174, 255, 187, 128], [61, 46, 138, 219, 151, 178, 240, 170, 255, 216, 128]], [[1, 112, 230, 250, 199, 191, 247, 159, 255, 255, 128], [166, 109, 228, 252, 211, 215, 255, 174, 128, 128, 128], [39, 77, 162, 232, 172, 180, 245, 178, 255, 255, 128]], [[1, 52, 220, 246, 198, 199, 249, 220, 255, 255, 128], [124, 74, 191, 243, 183, 193, 250, 221, 255, 255, 128], [24, 71, 130, 219, 154, 170, 243, 182, 255, 255, 128]], [[1, 182, 225, 249, 219, 240, 255, 224, 128, 128, 128], [149, 150, 226, 252, 216, 205, 255, 171, 128, 128, 128], [28, 108, 170, 242, 183, 194, 254, 223, 255, 255, 128]], [[1, 81, 230, 252, 204, 203, 255, 192, 128, 128, 128], [123, 102, 209, 247, 188, 196, 255, 233, 128, 128, 128], [20, 95, 153, 243, 164, 173, 255, 203, 128, 128, 128]], [[1, 222, 248, 255, 216, 213, 128, 128, 128, 128, 128], [168, 175, 246, 252, 235, 205, 255, 255, 128, 128, 128], [47, 116, 215, 255, 211, 212, 255, 255, 128, 128, 128]], [[1, 121, 236, 253, 212, 214, 255, 255, 128, 128, 128], [141, 84, 213, 252, 201, 202, 255, 219, 128, 128, 128], [42, 80, 160, 240, 162, 185, 255, 205, 128, 128, 128]], [[1, 1, 255, 128, 128, 128, 128, 128, 128, 128, 128], [244, 1, 255, 128, 128, 128, 128, 128, 128, 128, 128], [238, 1, 255, 128, 128, 128, 128, 128, 128, 128, 128]]]];
// ---------------------------------------------------------------------------
// entropymode.c + vp8_entropymodedata.h — mode/segmentation tables
// ---------------------------------------------------------------------------

/// `sub_mv_ref_prob` — default short-tree probabilities for the sub-MV reference (used when no neighbour context applies). RFC 6386 §17.4.
#[rustfmt::skip]
pub const SUB_MV_REF_PROB: [Prob; 3] = [180, 162, 25];
/// `vp8_sub_mv_ref_prob2` — context-dependent sub-MV-ref probabilities, indexed by `[SUBMVREF context][tree node]`. RFC 6386 §17.4.
#[rustfmt::skip]
pub const VP8_SUB_MV_REF_PROB2: [[Prob; 3]; 5] = [[147, 136, 18], [106, 145, 1], [179, 121, 1], [223, 1, 34], [208, 1, 1]];
/// `vp8_mbsplits` — the four MB-partition layouts (16 sub-block indices each), enumerating the half/quarter/eighth and 4x4 splits. RFC 6386 §17.3 (Figure 18).
#[rustfmt::skip]
pub const VP8_MBSPLITS: [[i32; 16]; 4] = [[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1], [0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1], [0, 0, 1, 1, 0, 0, 1, 1, 2, 2, 3, 3, 2, 2, 3, 3], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]];
/// `vp8_mbsplit_count` — number of distinct sub-blocks in each layout. RFC 6386 §17.3.
#[rustfmt::skip]
pub const VP8_MBSPLIT_COUNT: [i32; 4] = [2, 2, 4, 16];
/// `vp8_mbsplit_probs` — default probabilities for the MB-split tree. RFC 6386 §17.3.
#[rustfmt::skip]
pub const VP8_MBSPLIT_PROBS: [Prob; 3] = [110, 111, 150];
/// `vp8_bmode_tree` — decoding tree for the 10 intra 4x4 modes. RFC 6386 §11.5 Figure 11.1 (one-dimensional encoding).
#[rustfmt::skip]
pub const VP8_BMODE_TREE: [TreeIndex; 18] = [0, 2, -1, 4, -2, 6, 8, 12, -3, 10, -5, -6, -4, 14, -7, 16, -8, -9];
/// `vp8_ymode_tree` — decoding tree for intra Y-modes on an interframe. RFC 6386 §16.1.
#[rustfmt::skip]
pub const VP8_YMODE_TREE: [TreeIndex; 8] = [0, 2, 4, 6, -1, -2, -3, -4];
/// `vp8_kf_ymode_tree` — decoding tree for intra Y-modes on a keyframe. RFC 6386 §11.2.
#[rustfmt::skip]
pub const VP8_KF_YMODE_TREE: [TreeIndex; 8] = [-4, 2, 4, 6, 0, -1, -2, -3];
/// `vp8_uv_mode_tree` — decoding tree for intra UV-modes. RFC 6386 §11.2 / §16.1.
#[rustfmt::skip]
pub const VP8_UV_MODE_TREE: [TreeIndex; 6] = [0, 2, -1, 4, -2, -3];
/// `vp8_mbsplit_tree` — decoding tree selecting the MB-partition layout. RFC 6386 §17.3.
#[rustfmt::skip]
pub const VP8_MBSPLIT_TREE: [TreeIndex; 6] = [-3, 2, -2, 4, 0, -1];
/// `vp8_mv_ref_tree` — decoding tree selecting one of the 5 inter modes for a macroblock. RFC 6386 §16.2.
#[rustfmt::skip]
pub const VP8_MV_REF_TREE: [TreeIndex; 8] = [-7, 2, -5, 4, -6, 6, -8, -9];
/// `vp8_sub_mv_ref_tree` — decoding tree for the 4 sub-MV ref modes. RFC 6386 §17.4.
#[rustfmt::skip]
pub const VP8_SUB_MV_REF_TREE: [TreeIndex; 6] = [-10, 2, -11, 4, -12, -13];
/// `vp8_small_mvtree` — decoding tree for short (0..7) MV magnitudes. RFC 6386 §17.1.
#[rustfmt::skip]
pub const VP8_SMALL_MVTREE: [TreeIndex; 14] = [2, 8, 4, 6, 0, -1, -2, -3, 10, 12, -4, -5, -6, -7];
/// Encoder codewords for `VP8_BMODE_TREE`. RFC 6386 §11.5.
#[rustfmt::skip]
pub const VP8_BMODE_ENCODINGS: [Token; 10] = [Token { value: 0, len: 1 }, Token { value: 2, len: 2 }, Token { value: 6, len: 3 }, Token { value: 28, len: 5 }, Token { value: 30, len: 5 }, Token { value: 58, len: 6 }, Token { value: 59, len: 6 }, Token { value: 62, len: 6 }, Token { value: 126, len: 7 }, Token { value: 127, len: 7 }];

/// Encoder codewords for inter Y-modes. RFC 6386 §16.1.
#[rustfmt::skip]
pub const VP8_YMODE_ENCODINGS: [Token; 5] = [Token { value: 0, len: 1 }, Token { value: 4, len: 3 }, Token { value: 5, len: 3 }, Token { value: 6, len: 3 }, Token { value: 7, len: 3 }];

/// Encoder codewords for keyframe Y-modes. RFC 6386 §11.2.
#[rustfmt::skip]
pub const VP8_KF_YMODE_ENCODINGS: [Token; 5] = [Token { value: 4, len: 3 }, Token { value: 5, len: 3 }, Token { value: 6, len: 3 }, Token { value: 7, len: 3 }, Token { value: 0, len: 1 }];

/// Encoder codewords for UV-modes. RFC 6386 §11.2 / §16.1.
#[rustfmt::skip]
pub const VP8_UV_MODE_ENCODINGS: [Token; 4] = [Token { value: 0, len: 1 }, Token { value: 2, len: 2 }, Token { value: 6, len: 3 }, Token { value: 7, len: 3 }];

/// Encoder codewords for `VP8_MBSPLIT_TREE`. RFC 6386 §17.3.
#[rustfmt::skip]
pub const VP8_MBSPLIT_ENCODINGS: [Token; 4] = [Token { value: 6, len: 3 }, Token { value: 7, len: 3 }, Token { value: 2, len: 2 }, Token { value: 0, len: 1 }];

/// Encoder codewords for inter modes. RFC 6386 §16.2.
#[rustfmt::skip]
pub const VP8_MV_REF_ENCODING_ARRAY: [Token; 5] = [Token { value: 2, len: 2 }, Token { value: 6, len: 3 }, Token { value: 0, len: 1 }, Token { value: 14, len: 4 }, Token { value: 15, len: 4 }];

/// Encoder codewords for sub-MV-ref modes. RFC 6386 §17.4.
#[rustfmt::skip]
pub const VP8_SUB_MV_REF_ENCODING_ARRAY: [Token; 4] = [Token { value: 0, len: 1 }, Token { value: 2, len: 2 }, Token { value: 6, len: 3 }, Token { value: 7, len: 3 }];

/// Encoder codewords for short MV magnitudes. RFC 6386 §17.1.
#[rustfmt::skip]
pub const VP8_SMALL_MVENCODINGS: [Token; 8] = [Token { value: 0, len: 3 }, Token { value: 1, len: 3 }, Token { value: 2, len: 3 }, Token { value: 3, len: 3 }, Token { value: 4, len: 3 }, Token { value: 5, len: 3 }, Token { value: 6, len: 3 }, Token { value: 7, len: 3 }];

/// `vp8_ymode_prob` — default probabilities for inter Y-mode tree. RFC 6386 §16.1.
#[rustfmt::skip]
pub const VP8_YMODE_PROB: [Prob; 4] = [112, 86, 140, 37];
/// `vp8_kf_ymode_prob` — default probabilities for keyframe Y-mode tree. RFC 6386 §11.2.
#[rustfmt::skip]
pub const VP8_KF_YMODE_PROB: [Prob; 4] = [145, 156, 163, 128];
/// `vp8_uv_mode_prob` — default probabilities for inter UV-mode tree. RFC 6386 §16.1.
#[rustfmt::skip]
pub const VP8_UV_MODE_PROB: [Prob; 3] = [162, 101, 204];
/// `vp8_kf_uv_mode_prob` — default probabilities for keyframe UV-mode tree. RFC 6386 §11.2.
#[rustfmt::skip]
pub const VP8_KF_UV_MODE_PROB: [Prob; 3] = [142, 114, 183];
/// `vp8_bmode_prob` — default probabilities for the intra 4x4 mode tree, when neighbours are unavailable. RFC 6386 §11.5.
#[rustfmt::skip]
pub const VP8_BMODE_PROB: [Prob; 9] = [120, 90, 79, 133, 87, 85, 80, 111, 151];
/// `vp8_kf_bmode_prob` — keyframe intra 4x4 mode probabilities conditioned on the modes of the above and left sub-blocks: `[above_mode][left_mode][tree_node]`. RFC 6386 §11.5 Table 11.5.
#[rustfmt::skip]
pub const VP8_KF_BMODE_PROB: [[[Prob; 9]; 10]; 10] = [[[231, 120, 48, 89, 115, 113, 120, 152, 112], [152, 179, 64, 126, 170, 118, 46, 70, 95], [175, 69, 143, 80, 85, 82, 72, 155, 103], [56, 58, 10, 171, 218, 189, 17, 13, 152], [144, 71, 10, 38, 171, 213, 144, 34, 26], [114, 26, 17, 163, 44, 195, 21, 10, 173], [121, 24, 80, 195, 26, 62, 44, 64, 85], [170, 46, 55, 19, 136, 160, 33, 206, 71], [63, 20, 8, 114, 114, 208, 12, 9, 226], [81, 40, 11, 96, 182, 84, 29, 16, 36]], [[134, 183, 89, 137, 98, 101, 106, 165, 148], [72, 187, 100, 130, 157, 111, 32, 75, 80], [66, 102, 167, 99, 74, 62, 40, 234, 128], [41, 53, 9, 178, 241, 141, 26, 8, 107], [104, 79, 12, 27, 217, 255, 87, 17, 7], [74, 43, 26, 146, 73, 166, 49, 23, 157], [65, 38, 105, 160, 51, 52, 31, 115, 128], [87, 68, 71, 44, 114, 51, 15, 186, 23], [47, 41, 14, 110, 182, 183, 21, 17, 194], [66, 45, 25, 102, 197, 189, 23, 18, 22]], [[88, 88, 147, 150, 42, 46, 45, 196, 205], [43, 97, 183, 117, 85, 38, 35, 179, 61], [39, 53, 200, 87, 26, 21, 43, 232, 171], [56, 34, 51, 104, 114, 102, 29, 93, 77], [107, 54, 32, 26, 51, 1, 81, 43, 31], [39, 28, 85, 171, 58, 165, 90, 98, 64], [34, 22, 116, 206, 23, 34, 43, 166, 73], [68, 25, 106, 22, 64, 171, 36, 225, 114], [34, 19, 21, 102, 132, 188, 16, 76, 124], [62, 18, 78, 95, 85, 57, 50, 48, 51]], [[193, 101, 35, 159, 215, 111, 89, 46, 111], [60, 148, 31, 172, 219, 228, 21, 18, 111], [112, 113, 77, 85, 179, 255, 38, 120, 114], [40, 42, 1, 196, 245, 209, 10, 25, 109], [100, 80, 8, 43, 154, 1, 51, 26, 71], [88, 43, 29, 140, 166, 213, 37, 43, 154], [61, 63, 30, 155, 67, 45, 68, 1, 209], [142, 78, 78, 16, 255, 128, 34, 197, 171], [41, 40, 5, 102, 211, 183, 4, 1, 221], [51, 50, 17, 168, 209, 192, 23, 25, 82]], [[125, 98, 42, 88, 104, 85, 117, 175, 82], [95, 84, 53, 89, 128, 100, 113, 101, 45], [75, 79, 123, 47, 51, 128, 81, 171, 1], [57, 17, 5, 71, 102, 57, 53, 41, 49], [115, 21, 2, 10, 102, 255, 166, 23, 6], [38, 33, 13, 121, 57, 73, 26, 1, 85], [41, 10, 67, 138, 77, 110, 90, 47, 114], [101, 29, 16, 10, 85, 128, 101, 196, 26], [57, 18, 10, 102, 102, 213, 34, 20, 43], [117, 20, 15, 36, 163, 128, 68, 1, 26]], [[138, 31, 36, 171, 27, 166, 38, 44, 229], [67, 87, 58, 169, 82, 115, 26, 59, 179], [63, 59, 90, 180, 59, 166, 93, 73, 154], [40, 40, 21, 116, 143, 209, 34, 39, 175], [57, 46, 22, 24, 128, 1, 54, 17, 37], [47, 15, 16, 183, 34, 223, 49, 45, 183], [46, 17, 33, 183, 6, 98, 15, 32, 183], [65, 32, 73, 115, 28, 128, 23, 128, 205], [40, 3, 9, 115, 51, 192, 18, 6, 223], [87, 37, 9, 115, 59, 77, 64, 21, 47]], [[104, 55, 44, 218, 9, 54, 53, 130, 226], [64, 90, 70, 205, 40, 41, 23, 26, 57], [54, 57, 112, 184, 5, 41, 38, 166, 213], [30, 34, 26, 133, 152, 116, 10, 32, 134], [75, 32, 12, 51, 192, 255, 160, 43, 51], [39, 19, 53, 221, 26, 114, 32, 73, 255], [31, 9, 65, 234, 2, 15, 1, 118, 73], [88, 31, 35, 67, 102, 85, 55, 186, 85], [56, 21, 23, 111, 59, 205, 45, 37, 192], [55, 38, 70, 124, 73, 102, 1, 34, 98]], [[102, 61, 71, 37, 34, 53, 31, 243, 192], [69, 60, 71, 38, 73, 119, 28, 222, 37], [68, 45, 128, 34, 1, 47, 11, 245, 171], [62, 17, 19, 70, 146, 85, 55, 62, 70], [75, 15, 9, 9, 64, 255, 184, 119, 16], [37, 43, 37, 154, 100, 163, 85, 160, 1], [63, 9, 92, 136, 28, 64, 32, 201, 85], [86, 6, 28, 5, 64, 255, 25, 248, 1], [56, 8, 17, 132, 137, 255, 55, 116, 128], [58, 15, 20, 82, 135, 57, 26, 121, 40]], [[164, 50, 31, 137, 154, 133, 25, 35, 218], [51, 103, 44, 131, 131, 123, 31, 6, 158], [86, 40, 64, 135, 148, 224, 45, 183, 128], [22, 26, 17, 131, 240, 154, 14, 1, 209], [83, 12, 13, 54, 192, 255, 68, 47, 28], [45, 16, 21, 91, 64, 222, 7, 1, 197], [56, 21, 39, 155, 60, 138, 23, 102, 213], [85, 26, 85, 85, 128, 128, 32, 146, 171], [18, 11, 7, 63, 144, 171, 4, 4, 246], [35, 27, 10, 146, 174, 171, 12, 26, 128]], [[190, 80, 35, 99, 180, 80, 126, 54, 45], [85, 126, 47, 87, 176, 51, 41, 20, 32], [101, 75, 128, 139, 118, 146, 116, 128, 85], [56, 41, 15, 176, 236, 85, 37, 9, 62], [146, 36, 19, 30, 171, 255, 97, 27, 20], [71, 30, 17, 119, 118, 255, 17, 18, 138], [101, 38, 60, 138, 55, 70, 43, 26, 142], [138, 45, 61, 62, 219, 1, 81, 188, 64], [32, 41, 20, 117, 151, 142, 20, 21, 163], [112, 19, 12, 61, 195, 128, 48, 4, 24]]];
// ---------------------------------------------------------------------------
// entropymv.c — motion-vector probability tables
// ---------------------------------------------------------------------------

/// Per-probability update probabilities for MV components (`[0] = row`, `[1] = col`). RFC 6386 §17.2.
#[rustfmt::skip]
pub const VP8_MV_UPDATE_PROBS: [MvContext; 2] = [
    MvContext { prob: [237, 246, 253, 253, 254, 254, 254, 254, 254, 254, 254, 254, 254, 254, 250, 250, 252, 254, 254] },
    MvContext { prob: [231, 243, 245, 253, 254, 254, 254, 254, 254, 254, 254, 254, 254, 254, 251, 251, 254, 254, 254] },
];

/// Default MV-component probabilities (`[0] = row`, `[1] = col`). RFC 6386 §17.1 / §17.2.
#[rustfmt::skip]
pub const VP8_DEFAULT_MV_CONTEXT: [MvContext; 2] = [
    MvContext { prob: [162, 128, 225, 146, 172, 147, 214, 39, 156, 128, 129, 132, 75, 145, 178, 206, 239, 254, 254] },
    MvContext { prob: [164, 128, 204, 170, 119, 235, 140, 230, 228, 128, 130, 130, 74, 148, 180, 203, 236, 254, 254] },
];

// ---------------------------------------------------------------------------
// modecont.c — inter-mode context table
// ---------------------------------------------------------------------------

/// `vp8_mode_contexts` — 6 inter-mode contexts derived from the neighbour MV counts; each row supplies the 4 node probabilities for `VP8_MV_REF_TREE`. RFC 6386 §16.3 (Table 30).
#[rustfmt::skip]
pub const VP8_MODE_CONTEXTS: [[i32; 4]; 6] = [[7, 1, 1, 143], [14, 18, 14, 107], [135, 64, 57, 68], [60, 56, 128, 65], [159, 134, 128, 34], [234, 188, 128, 28]];
// ---------------------------------------------------------------------------
// quant_common.c — DC/AC dequantizer lookups
// ---------------------------------------------------------------------------

/// `dc_qlookup` — DC quantization step size indexed by quantizer index (0..127). RFC 6386 §9.6 (Dequantization).
#[rustfmt::skip]
pub const DC_QLOOKUP: [i32; 128] = [4, 5, 6, 7, 8, 9, 10, 10, 11, 12, 13, 14, 15, 16, 17, 17, 18, 19, 20, 20, 21, 21, 22, 22, 23, 23, 24, 25, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 91, 93, 95, 96, 98, 100, 101, 102, 104, 106, 108, 110, 112, 114, 116, 118, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 143, 145, 148, 151, 154, 157];
/// `ac_qlookup` — AC quantization step size indexed by quantizer index (0..127). RFC 6386 §9.6 (Dequantization).
#[rustfmt::skip]
pub const AC_QLOOKUP: [i32; 128] = [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 119, 122, 125, 128, 131, 134, 137, 140, 143, 146, 149, 152, 155, 158, 161, 164, 167, 170, 173, 177, 181, 185, 189, 193, 197, 201, 205, 209, 213, 217, 221, 225, 229, 234, 239, 245, 249, 254, 259, 264, 269, 274, 279, 284];
// ---------------------------------------------------------------------------
// filter.c — sub-pel interpolation filter taps
// ---------------------------------------------------------------------------

/// `vp8_bilinear_filters` — 2-tap bilinear filter coefficients, one row per 1/8-pel offset. Rows sum to `VP8_FILTER_WEIGHT` (128). RFC 6386 §6.5.2.
#[rustfmt::skip]
pub const VP8_BILINEAR_FILTERS: [[i16; 2]; 8] = [[128, 0], [112, 16], [96, 32], [80, 48], [64, 64], [48, 80], [32, 96], [16, 112]];
/// `vp8_sub_pel_filters` — 6-tap sub-pixel filter coefficients. Indexed by the 8 1/8-pel offsets (row 0 = no-op pass-through). RFC 6386 §6.5.1.
#[rustfmt::skip]
pub const VP8_SUB_PEL_FILTERS: [[i16; 6]; 8] = [[0, 0, 128, 0, 0, 0], [0, -6, 123, 12, -1, 0], [2, -11, 108, 36, -8, 1], [0, -9, 93, 50, -6, 0], [3, -16, 77, 77, -16, 3], [0, -6, 50, 93, -9, 0], [1, -8, 36, 108, -11, 2], [0, -1, 12, 123, -6, 0]];
// ---------------------------------------------------------------------------
// blockd.c — block-to-context lookup tables
// ---------------------------------------------------------------------------

/// `vp8_block2left` — for each of the 25 sub-blocks (16 Y + 4 U + 4 V + 1 Y2), the index of the corresponding left-neighbour entropy context. libvpx convention (not specified in RFC 6386 verbatim; equivalent to the §13.3 ABOVE/LEFT context indexing).
#[rustfmt::skip]
pub const VP8_BLOCK2LEFT: [u8; 25] = [0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8];
/// `vp8_block2above` — for each sub-block, the index of its above-neighbour entropy context (libvpx convention; mirrors RFC 6386 §13.3 ABOVE/LEFT context indexing).
#[rustfmt::skip]
pub const VP8_BLOCK2ABOVE: [u8; 25] = [0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 4, 5, 6, 7, 6, 7, 8];
// ---------------------------------------------------------------------------
// setupintrarecon.c — intra-recon edge seed bytes
// ---------------------------------------------------------------------------

/// Top-row / above-edge seed byte for intra reconstruction; RFC 6386 §12.2
/// requires above-frame samples to be filled with 127.
pub const INTRA_RECON_ABOVE_SEED: u8 = 127;

/// Left-column seed byte for intra reconstruction; RFC 6386 §12.2 requires
/// left-of-frame samples to be filled with 129.
pub const INTRA_RECON_LEFT_SEED: u8 = 129;

