//! RTCD dispatch aliases generated by `vp8/common/rtcd_defs.pl` into
//! `vp8_only/vp8_rtcd.h`.
//!
//! On the verified single-arch `generic-gnu` build every dispatched
//! kernel collapses to a `#define X X_c` alias of its C reference
//! implementation. The Rust port mirrors that by `pub use`-renaming
//! each `_c` impl to the bare RTCD name.
//!
//! When SIMD lands these would become runtime function-pointer reads
//! initialised by `vp8_rtcd()` (see `crate::rtcd`).

pub use crate::dequantize::{
    vp8_dequant_idct_add_c as vp8_dequant_idct_add, vp8_dequantize_b_c as vp8_dequantize_b,
};

pub use crate::idct_blk::{
    vp8_dequant_idct_add_uv_block_c as vp8_dequant_idct_add_uv_block,
    vp8_dequant_idct_add_y_block_c as vp8_dequant_idct_add_y_block,
};

pub use crate::idctllm::{
    vp8_dc_only_idct_add_c as vp8_dc_only_idct_add, vp8_short_idct4x4llm_c as vp8_short_idct4x4llm,
    vp8_short_inv_walsh4x4_1_c as vp8_short_inv_walsh4x4_1,
    vp8_short_inv_walsh4x4_c as vp8_short_inv_walsh4x4,
};
