// Copyright (c) 2015 The WebM project authors. All Rights Reserved.
//
// Use of this source code is governed by a BSD-style license
// that can be found in the LICENSE file in the root of the source
// tree. An additional intellectual property rights grant can be found
// in the file PATENTS.  All contributing project authors may
// be found in the AUTHORS file in the root of the source tree.

// Rust port of vpx_dsp/vpx_dsp_rtcd.c.
//
// This C file owns the cross-codec DSP function-pointer table for the VP8/VP9
// RTCD (Run-Time CPU Dispatch) subsystem. It defines `RTCD_C` before including
// the generated `vpx_dsp_rtcd.h`, emitting `setup_rtcd_internal` (which
// populates the pointer table) and `vpx_dsp_rtcd()`, which wraps it in a
// per-translation-unit `once()` so population runs exactly once.
//
// On the generic-gnu (no-SIMD) build every dispatchable kernel collapses to a
// `#define` alias of its `_c` implementation, so `setup_rtcd_internal()` has an
// empty body and `vpx_dsp_rtcd()` is a no-op after the once-synchronisation.
// This port targets that build but preserves the symbol name `vpx_dsp_rtcd`
// and a `once` guard so the semantics match (idempotent, thread-safe).

use std::sync::Once;

/// The per-translation-unit `once` guard (C: `vpx_ports/vpx_once.h`).
static SETUP_RTCD_ONCE: Once = Once::new();

/// Mirror of the generated `static void setup_rtcd_internal(void)` in
/// `vpx_dsp_rtcd.h`. Empty on the generic (no-SIMD) build because every
/// dispatchable DSP kernel collapses to a `#define` alias of its `_c`
/// implementation.
fn setup_rtcd_internal() {
    // Empty: no SIMD function pointers to resolve in the generic build.
}

/// Public entry point of the cross-codec DSP RTCD subsystem.
/// Guarantees `setup_rtcd_internal` runs exactly once, regardless
/// of how many threads race to enter.
pub fn vpx_dsp_rtcd() {
    SETUP_RTCD_ONCE.call_once(setup_rtcd_internal);
}

// RTCD aliases generated by `vpx_dsp_rtcd.h` — on the generic-gnu build
// each `#define X X_c` collapses to a re-export. Only the intra-predictor
// variants currently used by callers are exposed here; add more as new
// callers appear.
pub use crate::intrapred::{
    vpx_d45e_predictor_4x4_c as vpx_d45e_predictor_4x4,
    vpx_d63e_predictor_4x4_c as vpx_d63e_predictor_4x4,
    vpx_d117_predictor_4x4_c as vpx_d117_predictor_4x4,
    vpx_d135_predictor_4x4_c as vpx_d135_predictor_4x4,
    vpx_d153_predictor_4x4_c as vpx_d153_predictor_4x4,
    vpx_d207_predictor_4x4_c as vpx_d207_predictor_4x4,
    vpx_dc_128_predictor_8x8_c as vpx_dc_128_predictor_8x8,
    vpx_dc_128_predictor_16x16_c as vpx_dc_128_predictor_16x16,
    vpx_dc_left_predictor_8x8_c as vpx_dc_left_predictor_8x8,
    vpx_dc_left_predictor_16x16_c as vpx_dc_left_predictor_16x16,
    vpx_dc_predictor_4x4_c as vpx_dc_predictor_4x4, vpx_dc_predictor_8x8_c as vpx_dc_predictor_8x8,
    vpx_dc_predictor_16x16_c as vpx_dc_predictor_16x16,
    vpx_dc_top_predictor_8x8_c as vpx_dc_top_predictor_8x8,
    vpx_dc_top_predictor_16x16_c as vpx_dc_top_predictor_16x16,
    vpx_h_predictor_8x8_c as vpx_h_predictor_8x8, vpx_h_predictor_16x16_c as vpx_h_predictor_16x16,
    vpx_he_predictor_4x4_c as vpx_he_predictor_4x4, vpx_tm_predictor_4x4_c as vpx_tm_predictor_4x4,
    vpx_tm_predictor_8x8_c as vpx_tm_predictor_8x8,
    vpx_tm_predictor_16x16_c as vpx_tm_predictor_16x16,
    vpx_v_predictor_8x8_c as vpx_v_predictor_8x8, vpx_v_predictor_16x16_c as vpx_v_predictor_16x16,
    vpx_ve_predictor_4x4_c as vpx_ve_predictor_4x4,
};
