// Literal Rust transliteration of vpx_scale/vpx_scale_rtcd.c
//
// Original C:
//     #include "./vpx_config.h"
//     #define RTCD_C
//     #include "./vpx_scale_rtcd.h"
//     #include "vpx_ports/vpx_once.h"
//
//     void vpx_scale_rtcd(void) { once(setup_rtcd_internal); }
//
// On the verified generic-gnu VP8-only decoder build, the generated
// vpx_scale_rtcd.h yields an empty setup_rtcd_internal body (every
// dispatched primitive collapses to a #define alias of its `_c`
// reference). The once() wrapper therefore guards an empty
// initialiser. We mirror that here: a file-local once flag, an empty
// setup routine, and the public entry point vpx_scale_rtcd().

use std::sync::Once;

// File-static once state, matching the per-translation-unit lock
// discipline of vpx_ports/vpx_once.h.
static SCALE_RTCD_ONCE: Once = Once::new();

// Generated by vpx_scale_rtcd.h under #ifdef RTCD_C. On the verified
// generic-gnu VP8-only decoder build the body is empty: all three YV12
// primitives (vp8_yv12_extend_frame_borders, vp8_yv12_copy_frame,
// vpx_yv12_copy_y) are #define aliases of their `_c` references in
// vpx_scale/generic/yv12extend.c, so there is nothing to assign.
fn setup_rtcd_internal() {}

// RTCD aliases from the generated `vpx_scale_rtcd.h` — on the
// generic-gnu build each `#define X X_c` collapses to a re-export.
pub use crate::yv12extend::{
    vp8_yv12_copy_frame_c as vp8_yv12_copy_frame,
    vp8_yv12_extend_frame_borders_c as vp8_yv12_extend_frame_borders,
};

/// Public entry point of the YV12 dispatch subsystem.
///
/// Safe to call from any thread at any time; idempotent. Must be
/// called before any of the dispatched YV12 primitives is invoked.

pub extern "C" fn vpx_scale_rtcd() {
    SCALE_RTCD_ONCE.call_once(setup_rtcd_internal);
}
